### PR TITLE
Add a multi-distro spec file to build procdump

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This commit simultaneously removes the old way to produce a Debian package.

Signed-off-by: Neal Gompa <ngompa13@gmail.com>

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This is a slightly tweaked version of the spec I used here: https://build.opensuse.org/package/show/home:Pharaoh_Atem:procdump/procdump

In this case, the spec can be driven from the Makefile so that you can build the Debian or RPM packages from the Makefile.

**Comment by jahabibi** [comment]
Everything looks good! We have been doing some housekeeping with procdump recently, could you please rebase your changes on top of master.

**Comment by Conan-Kudo** [comment]
@jahabibi I've rebased everything accordingly.

**Comment by Conan-Kudo** [comment]
@jahabibi Note that I filled out the changelog section of the spec with the actual release information from GitHub, as I figured that'd be useful for people to be able get the changelog easily on installed systems. If you'd rather not have a changelog, please let me know and I can roll it back to the generic "initial packaging" entry I previously had.

**Comment by Conan-Kudo** [comment]
@jahabibi Note that I filled out the changelog section of the spec with the actual release information from GitHub, as I figured that'd be useful for people to be able get the changelog easily on installed systems. The expectation, of course, would be that the changelog would be filled out for subsequent releases...

If you'd rather not have a changelog, please let me know and I can roll it back to the generic "initial packaging" entry I previously had.

**Comment by Conan-Kudo** [comment]
@jahabibi @josalem Can someone please review this, since I reworked this as requested?

**Comment by Conan-Kudo** [comment]
Hello, is there anyone there to review and merge this?

**Pull request merged**
