### PR TITLE
add -g option to specify gcore command to use

### PR DESCRIPTION
**Pull request by aaptel**

### CODE REVIEW

**Comment by josalem** [comment]
Could you provide details on the use case for these changes?  It looks like you aren't adding the ability to specify `gcore` options, but rather the ability to specify a whole different program to be executed when a "dump" triggers.  The variable naming is slightly off base if the end result is "specify dump executable".

**Comment by aaptel** [comment]
procdump ends up using the first gcore bin it finds in $PATH. If you want to use a different one this option allows you to path the full path to a different gcore bin.

**Comment by josalem** [comment]
I think it would be more appropriate to leave resolution of `gcore` up to the user.  If a user wants to use a different `gcore` binary, I would prefer they use `alias gcore <other gcore>` rather than add path walking logic to ProcDump.  In the future we plan on replacing `gcore` with a custom userspace dumper, but for now we're making it a required dependency of running ProcDump.  I will close this for now, and we can revisit the feature when we have removed the `gcore` dependency.

**Comment by aaptel** [comment]
shell alias wouldnt work unfortunately. user would have to edit PATH env var or put the binary somewhere in PATH.

**Pull request closed without merging**
