### PR TITLE
Fixes to make procdump build and run against a wider array of Linux distributions

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This PR contains changes to make procdump build and run correctly across a wider array of distributions.

The fixes range from dropping Debianisms in the integration tests to adjustments to the Makefiles to make the tool build properly on RHEL/CentOS 7.

This was tested to successfully build procdump on the following Linux distributions:

* CentOS 7
* Fedora 26 and Fedora 27
* Mageia 6
* Ubuntu 14.04 and Ubuntu 16.04

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@josalem I also considered including a spec file for you to use for building packages in this PR, but I wasn't sure if you wanted one.

**Comment by Conan-Kudo** [comment]
Here's Debian and RPM packages built from a spec file using OBS: https://build.opensuse.org/package/show/home:Pharaoh_Atem:procdump/procdump

@josalem If you'd like, I can contribute the spec in this PR and adjust the Makefile to be able to build Debian and RPM packages using it.

**Comment by josalem** [comment]
@Conan-Kudo, I retargeted the PR to development.  You will need to merge latest changes before I can complete the PR.  I'll put the review in once you've merged things on your end.  As for the spec, let's put that in a separate PR.  Thanks for contributing!

**Comment by Conan-Kudo** [comment]
@josalem Rebased now.

**Pull request merged**
